/**
 * @module keyPanel
 * Discord UI panel for license key management
 */

import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  EmbedBuilder,
  TextChannel,
  ButtonInteraction,
  Message,
} from 'discord.js';
import { createKey } from './keyGenerator.js';
import { listLicenseKeys, getLicenseStats } from '../database.js';
import { formatTimestamp } from '../utils.js';
import { logger } from '../logger.js';

export class KeyPanel {
  private panelMessage: Message | null = null;

  constructor(private channel: TextChannel) {}

  async sendPanel(): Promise<void> {
    // Delete old panel if exists
    if (this.panelMessage) {
      try { await this.panelMessage.delete(); } catch {}
    }

    const stats = await getLicenseStats();

    const embed = new EmbedBuilder()
      .setColor(0x5865F2)
      .setTitle('License Key Management')
      .setDescription([
        'Generate single-use license keys for premium access.',
        '',
        '**Statistics**',
        `Total Keys: ${stats.total}`,
        `Used: ${stats.used}`,
        `Available: ${stats.unused}`,
        '',
        '**User Commands**',
        '`/activate <key>` - Activate your premium license',
        '`/premium` - Check your premium status',
      ].join('\n'))
      .setTimestamp();

    const row = new ActionRowBuilder<ButtonBuilder>()
      .addComponents(
        new ButtonBuilder()
          .setCustomId('generate_key')
          .setLabel('Generate Key')
          .setStyle(ButtonStyle.Primary),
        new ButtonBuilder()
          .setCustomId('list_keys')
          .setLabel('List Keys')
          .setStyle(ButtonStyle.Secondary),
        new ButtonBuilder()
          .setCustomId('refresh_stats')
          .setLabel('Refresh Stats')
          .setStyle(ButtonStyle.Secondary),
      );

    this.panelMessage = await this.channel.send({
      embeds: [embed],
      components: [row],
    });

    logger.debug('License panel sent to channel', { channelId: this.channel.id });
  }

  async handleInteraction(interaction: ButtonInteraction): Promise<void> {
    const { customId } = interaction;

    if (customId === 'generate_key') {
      await this.handleGenerate(interaction);
    } else if (customId === 'list_keys') {
      await this.handleList(interaction);
    } else if (customId === 'refresh_stats') {
      await this.handleRefresh(interaction);
    }
  }

  private async handleGenerate(interaction: ButtonInteraction): Promise<void> {
    await interaction.deferReply({ ephemeral: true });

    const key = await createKey(interaction.user.id);

    const embed = new EmbedBuilder()
      .setColor(0x00AAFF)
      .setTitle('License Key Generated')
      .addFields(
        { name: 'Key', value: `\`${key}\``, inline: false },
        { name: 'Type', value: 'Single-use', inline: true },
        { name: 'Expiration', value: 'Never', inline: true },
      )
      .setTimestamp();

    await interaction.editReply({ embeds: [embed] });

    // Refresh the panel to update stats
    await this.sendPanel();

    logger.info(`License key generated by ${interaction.user.id}`, { key });
  }

  private async handleList(interaction: ButtonInteraction): Promise<void> {
    await interaction.deferReply({ ephemeral: true });

    const keys = await listLicenseKeys(25);

    if (keys.length === 0) {
      await interaction.editReply({ content: 'No license keys have been generated.' });
      return;
    }

    const embed = new EmbedBuilder()
      .setColor(0x5865F2)
      .setTitle(`License Keys (${keys.length})`)
      .setTimestamp();

    for (const k of keys.slice(0, 15)) {
      const status = k.used 
        ? `Used by <@${k.usedBy}>` 
        : 'Available';
      
      embed.addFields({
        name: `\`${k.key}\``,
        value: `${status} | Created ${formatTimestamp(k.createdAt)}`,
        inline: false,
      });
    }

    if (keys.length > 15) {
      embed.setFooter({ text: `Showing 15 of ${keys.length} keys` });
    }

    await interaction.editReply({ embeds: [embed] });
  }

  private async handleRefresh(interaction: ButtonInteraction): Promise<void> {
    await interaction.deferReply({ ephemeral: true });
    await this.sendPanel();
    await interaction.editReply({ content: 'Panel refreshed.' });
  }
}
